### PR TITLE
CI

### PR DESCRIPTION
**Pull request by clytaemnestra**
I've added CI script, which:
* creates virtual environment & installs all dependencies,
* runs the code,
* contains cronjob, which runs every day at 10 AM. 

I tested it on my branch and it works. It's necessary to enable the CircleCI build again after the code is merged.

### CODE REVIEW

**Review by honzajavorek — APPROVED** [review]
Looks about right! Are you using CircleCI just because the original project has been using it, or is there a good reason to use it over GitHub Actions? Either way, it's your call and your preference, I'm pretty much indifferent. I prefer CircleCI for serious stuff, perhaps only because I'm used to it from the past. I prefer GitHub Actions for anything else where I don't really care, as they have the advantage of being already part of the GitHub platform and contributions from others to the CI settings etc. are easier.

**Comment by clytaemnestra** [comment]
> Looks about right! Are you using CircleCI just because the original project has been using it, or is there a good reason to use it over GitHub Actions? Either way, it's your call and your preference, I'm pretty much indifferent. I prefer CircleCI for serious stuff, perhaps only because I'm used to it from the past. I prefer GitHub Actions for anything else where I don't really care, as they have the advantage of being already part of the GitHub platform and contributions from others to the CI settings etc. are easier.

Thanks! I'm using CircleCI as it was in the last project and also I have experience with it. To me it looks like CircleCI has more features and is more advanced. I've used GitHub actions for quality pipelines, but that's about it. If you're indifferent about it, I'd prefer to keep it in CircleCI. I'm not sure if it's possible to create a service account, so it's not connected with my personal GitHub action, but with Pyvec for example, where everyone from the organization would have admin rights. I'll try to google it out.

**Comment by honzajavorek** [comment]
I think CircleCI just mirrors the GitHub permissions.

Screenshot 2022-10-10 at 12 50 22

**Comment by honzajavorek** [comment]
It needs token. @clytaemnestra can you access https://app.circleci.com/settings/project/github/pyvec/pyvo-bot/environment-variables ?

**Comment by clytaemnestra** [comment]
> It needs token. @clytaemnestra can you access https://app.circleci.com/settings/project/github/pyvec/pyvo-bot/environment-variables ?

Yea, I'll set it up today.

**Pull request merged**
